### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by Hawkiethehawk** [Foreverddb/legym-auto#2]
![3](https://user-images.githubusercontent.com/104438279/165504387-afa5b8fa-df72-4645-9e00-ae5dfe1a64dd.png)
我的copy运行失败，存在如下问题，请问是什么情况呢？

**Comment by Foreverddb** [comment]
这是因为你这个关键词对应了两个活动，而该类型活动乐健一天只允许报名一次，所以报名失败了一个，也导致后面签到失败。建议关键词改成只能对应到一个活动的（比如综训馆/体育馆）

**Comment by Hawkiethehawk** [comment]
多谢T T 麻烦了
